name: Close Pull Request

on:
  pull_request:
    types:
      - opened
    paths:
      - "Formula/*.rb"
  workflow_dispatch:

concurrency:
  group: close-pr
  cancel-in-progress: false

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Delete
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: git push origin --delete "$BRANCH_NAME"
