name: Close Pull Request

on:
  pull_request:
    types:
      - opened
    paths:
      - "Formula/*.rb"

concurrency:
  group: close-pr
  cancel-in-progress: false

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Delete
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: git push origin --delete "$BRANCH_NAME"
